site_name: adabmDCApy
site_dir: site
docs_dir: docs
nav:
  - Home: index.md
  - Installation: installation.md
  - Input data and preprocessing: preprocessing.md
  - Training: training.md
  - Applications: applications.md
  - Quicklist: quicklist.md
  - Script arguments: script_arguments.md
  - Python APIs:
      - Overview: api/README.md
      - Fasta utils: api/adabmDCA.fasta.md
      - Compute statistics: api/adabmDCA.stats.md
      - DCA utils: api/adabmDCA.dca.md
      - Import and export: api/adabmDCA.io.md
      - Sampling functions: api/adabmDCA.sampling.md
      - Utilities: api/adabmDCA.utils.md
      - Dataset class: api/adabmDCA.dataset.md
      - Statistical mechanics functions: api/adabmDCA.statmech.md
      - Train/test split: api/adabmDCA.cobalt.md
      - Training functions: api/adabmDCA.training.md
      - Special functions: api/adabmDCA.functional.md
      - Helper functions for plotting: api/adabmDCA.plot.md

theme: 
  name: material
  features:
    - content.code.annotate # Optional syntax highlighting
    - content.tabs.link     # Optional tabs support

markdown_extensions:
    - pymdownx.arithmatex:  # Enables LaTeX math
        generic: true       # Uses KaTeX by default
    - pymdownx.snippets
    - admonition  # Enables basic !!! syntax
    - pymdownx.details  # For richer styles (optional)

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
